export const PLANETS = [
  {
    id: "mercury",
    name: "Mercury",
    position: { x: -50, y: 0, z: 0 },
    radius: 0.35,
    axialTilt: 0.034,
    rotationSpeed: 0.0008,
    texture: "2k_mercury.webp",
    camera: { x: -50, y: 0, z: 1.5 },
    info: {
      distanceFromSun: "57.9M km",
      radius: "2,440 km",
      dayLength: "1,408 hours",
      orbitalSpeed: "47.4 km/s",
      axialTilt: "0.034°",
      gravity: "3.7 m/s²",
      moons: "0",
      atmosphere: "Thin exosphere",
      temperature: "−180°C to +430°C",
      age: "4.5 billion years",
    },
  },
  {
    id: "venus",
    name: "Venus",
    position: { x: -28, y: 0, z: 0 },
    radius: 0.95,
    axialTilt: 177.4,
    rotationSpeed: 0.0005,
    camera: { x: -28, y: 0, z: 2.5 },
    layers: [
      {
        type: "day",
        map: "2k_venus_surface.webp",
      },
      {
        type: "clouds",
        map: "2k_venus_atmosphere.webp",
        scale: 1.005,
        rotationSpeed: 0.0023,
      },
    ],
    info: {
      distanceFromSun: "108.2M km",
      radius: "6,051 km",
      dayLength: "5,832 hours",
      orbitalSpeed: "35.0 km/s",
      axialTilt: "177.4°",
      gravity: "8.87 m/s²",
      moons: "0",
      atmosphere: "96% CO₂",
      temperature: "+465°C average",
      age: "4.5 billion years",
    },
  },
  {
    id: "earth",
    name: "Earth",
    position: { x: 0, y: 0, z: 0 },
    radius: 1,
    axialTilt: 23.4,
    rotationSpeed: 0.002,
    camera: { x: 0, y: 0, z: 3 },
    layers: [
      {
        type: "day",
        map: "8k_earth_daymap.webp",
        specularMap: "8k_earth_specular_map.webp",
        normalMap: "8k_earth_normal_map.webp",
      },
      {
        type: "night",
        map: "8k_earth_nightmap.webp",
      },
      {
        type: "clouds",
        map: "8k_earth_clouds.webp",
        scale: 1.005,
        rotationSpeed: 0.0023,
      },
    ],
    info: {
      distanceFromSun: "149.6M km",
      radius: "6,371 km",
      dayLength: "24 hours",
      orbitalSpeed: "29.8 km/s",
      axialTilt: "23.4°",
      gravity: "9.8 m/s²",
      moons: "1",
      atmosphere: "78% N₂, 21% O₂",
      temperature: "−88°C to +58°C",
      age: "4.5 billion years",
    },
  },
  {
    id: "mars",
    name: "Mars",
    position: { x: 20, y: 0, z: 0 },
    radius: 0.53,
    axialTilt: 25.2,
    rotationSpeed: 0.0019,
    texture: "2k_mars.webp",
    camera: { x: 20, y: 0, z: 1.8 },
    info: {
      distanceFromSun: "227.9M km",
      radius: "3,390 km",
      dayLength: "24.6 hours",
      orbitalSpeed: "24.1 km/s",
      axialTilt: "25.2°",
      gravity: "3.72 m/s²",
      moons: "2",
      atmosphere: "95% CO₂",
      temperature: "−143°C to +35°C",
      age: "4.5 billion years",
    },
  },
  {
    id: "jupiter",
    name: "Jupiter",
    position: { x: 60, y: 0, z: 0 },
    radius: 4,
    axialTilt: 3.1,
    rotationSpeed: 0.0045,
    texture: "2k_jupiter.webp",
    camera: { x: 60, y: 0, z: 10 },
    info: {
      distanceFromSun: "778.5M km",
      radius: "69,911 km",
      dayLength: "9.9 hours",
      orbitalSpeed: "13.1 km/s",
      axialTilt: "3.1°",
      gravity: "24.8 m/s²",
      moons: "95",
      atmosphere: "90% H₂, 10% He",
      temperature: "−145°C average",
      age: "4.5 billion years",
    },
  },
  {
    id: "saturn",
    name: "Saturn",
    position: { x: 115, y: 0, z: 0 },
    radius: 3.5,
    axialTilt: 26.7,
    rotationSpeed: 0.004,
    texture: "2k_saturn.webp",
    camera: { x: 115, y: 0, z: 9 },
    info: {
      distanceFromSun: "1,432M km",
      radius: "58,232 km",
      dayLength: "10.7 hours",
      orbitalSpeed: "9.7 km/s",
      axialTilt: "26.7°",
      gravity: "10.4 m/s²",
      moons: "146",
      atmosphere: "96% H₂, 3% He",
      temperature: "−178°C average",
      age: "4.5 billion years",
    },
  },
  {
    id: "uranus",
    name: "Uranus",
    position: { x: 165, y: 0, z: 0 },
    radius: 2,
    axialTilt: 97.8,
    rotationSpeed: 0.003,
    texture: "2k_uranus.webp",
    camera: { x: 165, y: 0, z: 5.5 },
    info: {
      distanceFromSun: "2,867M km",
      radius: "25,362 km",
      dayLength: "17.2 hours",
      orbitalSpeed: "6.8 km/s",
      axialTilt: "97.8°",
      gravity: "8.87 m/s²",
      moons: "27",
      atmosphere: "83% H₂, 15% He, 2% CH₄",
      temperature: "−224°C average",
      age: "4.5 billion years",
    },
  },
  {
    id: "neptune",
    name: "Neptune",
    position: { x: 210, y: 0, z: 0 },
    radius: 1.9,
    axialTilt: 28.3,
    rotationSpeed: 0.0032,
    texture: "2k_neptune.webp",
    camera: { x: 210, y: 0, z: 5.5 },
    info: {
      distanceFromSun: "4,515M km",
      radius: "24,622 km",
      dayLength: "16.1 hours",
      orbitalSpeed: "5.4 km/s",
      axialTilt: "28.3°",
      gravity: "11.2 m/s²",
      moons: "16",
      atmosphere: "80% H₂, 19% He, 1% CH₄",
      temperature: "−218°C average",
      age: "4.5 billion years",
    },
  },
];
